/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as DeviceRouteRouteImport } from './routes/device/route'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as WorkspacesRouteRouteImport } from './routes/workspaces/route'
import { Route as AppAuditRouteImport } from './routes/_app/audit'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppMembersRouteImport } from './routes/_app/members'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppVaultsRouteImport } from './routes/_app/vaults'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as DeviceIndexRouteImport } from './routes/device/index'
import { Route as DeviceConfirmationRouteImport } from './routes/device/confirmation'
import { Route as WorkspacesJoinRouteImport } from './routes/workspaces/join'
import { Route as AppVaultsIndexRouteImport } from './routes/_app/vaults/index'
import { Route as AppVaultsVaultIdRouteImport } from './routes/_app/vaults/$vaultId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceRouteRoute = DeviceRouteRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesRouteRoute = WorkspacesRouteRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppMembersRoute = AppMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppVaultsRoute = AppVaultsRouteImport.update({
  id: '/vaults',
  path: '/vaults',
  getParentRoute: () => AppRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const DeviceIndexRoute = DeviceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DeviceRouteRoute,
} as any)
const DeviceConfirmationRoute = DeviceConfirmationRouteImport.update({
  id: '/confirmation',
  path: '/confirmation',
  getParentRoute: () => DeviceRouteRoute,
} as any)
const WorkspacesJoinRoute = WorkspacesJoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => WorkspacesRouteRoute,
} as any)
const AppVaultsIndexRoute = AppVaultsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppVaultsRoute,
} as any)
const AppVaultsVaultIdRoute = AppVaultsVaultIdRouteImport.update({
  id: '/$vaultId',
  path: '/$vaultId',
  getParentRoute: () => AppVaultsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/device': typeof DeviceRouteRouteWithChildren
  '/workspaces': typeof WorkspacesRouteRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/audit': typeof AppAuditRoute
  '/dashboard': typeof AppDashboardRoute
  '/members': typeof AppMembersRoute
  '/settings': typeof AppSettingsRoute
  '/vaults': typeof AppVaultsRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/device/confirmation': typeof DeviceConfirmationRoute
  '/workspaces/join': typeof WorkspacesJoinRoute
  '/device/': typeof DeviceIndexRoute
  '/vaults/$vaultId': typeof AppVaultsVaultIdRoute
  '/vaults/': typeof AppVaultsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/workspaces': typeof WorkspacesRouteRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/audit': typeof AppAuditRoute
  '/dashboard': typeof AppDashboardRoute
  '/members': typeof AppMembersRoute
  '/settings': typeof AppSettingsRoute
  '/auth/login': typeof AuthLoginRoute
  '/device/confirmation': typeof DeviceConfirmationRoute
  '/workspaces/join': typeof WorkspacesJoinRoute
  '/device': typeof DeviceIndexRoute
  '/vaults/$vaultId': typeof AppVaultsVaultIdRoute
  '/vaults': typeof AppVaultsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/device': typeof DeviceRouteRouteWithChildren
  '/workspaces': typeof WorkspacesRouteRouteWithChildren
  '/_app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/members': typeof AppMembersRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/vaults': typeof AppVaultsRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/device/confirmation': typeof DeviceConfirmationRoute
  '/workspaces/join': typeof WorkspacesJoinRoute
  '/device/': typeof DeviceIndexRoute
  '/_app/vaults/$vaultId': typeof AppVaultsVaultIdRoute
  '/_app/vaults/': typeof AppVaultsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/device'
    | '/workspaces'
    | '/onboarding'
    | '/audit'
    | '/dashboard'
    | '/members'
    | '/settings'
    | '/vaults'
    | '/auth/login'
    | '/device/confirmation'
    | '/workspaces/join'
    | '/device/'
    | '/vaults/$vaultId'
    | '/vaults/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/workspaces'
    | '/onboarding'
    | '/audit'
    | '/dashboard'
    | '/members'
    | '/settings'
    | '/auth/login'
    | '/device/confirmation'
    | '/workspaces/join'
    | '/device'
    | '/vaults/$vaultId'
    | '/vaults'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/device'
    | '/workspaces'
    | '/_app'
    | '/onboarding'
    | '/_app/audit'
    | '/_app/dashboard'
    | '/_app/members'
    | '/_app/settings'
    | '/_app/vaults'
    | '/auth/login'
    | '/device/confirmation'
    | '/workspaces/join'
    | '/device/'
    | '/_app/vaults/$vaultId'
    | '/_app/vaults/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  DeviceRouteRoute: typeof DeviceRouteRouteWithChildren
  WorkspacesRouteRoute: typeof WorkspacesRouteRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device': {
      id: '/device'
      path: '/device'
      fullPath: '/device'
      preLoaderRoute: typeof DeviceRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces': {
      id: '/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof WorkspacesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/members': {
      id: '/_app/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AppMembersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vaults': {
      id: '/_app/vaults'
      path: '/vaults'
      fullPath: '/vaults'
      preLoaderRoute: typeof AppVaultsRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/device/': {
      id: '/device/'
      path: '/'
      fullPath: '/device/'
      preLoaderRoute: typeof DeviceIndexRouteImport
      parentRoute: typeof DeviceRouteRoute
    }
    '/device/confirmation': {
      id: '/device/confirmation'
      path: '/confirmation'
      fullPath: '/device/confirmation'
      preLoaderRoute: typeof DeviceConfirmationRouteImport
      parentRoute: typeof DeviceRouteRoute
    }
    '/workspaces/join': {
      id: '/workspaces/join'
      path: '/join'
      fullPath: '/workspaces/join'
      preLoaderRoute: typeof WorkspacesJoinRouteImport
      parentRoute: typeof WorkspacesRouteRoute
    }
    '/_app/vaults/': {
      id: '/_app/vaults/'
      path: '/'
      fullPath: '/vaults/'
      preLoaderRoute: typeof AppVaultsIndexRouteImport
      parentRoute: typeof AppVaultsRoute
    }
    '/_app/vaults/$vaultId': {
      id: '/_app/vaults/$vaultId'
      path: '/$vaultId'
      fullPath: '/vaults/$vaultId'
      preLoaderRoute: typeof AppVaultsVaultIdRouteImport
      parentRoute: typeof AppVaultsRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface DeviceRouteRouteChildren {
  DeviceConfirmationRoute: typeof DeviceConfirmationRoute
  DeviceIndexRoute: typeof DeviceIndexRoute
}

const DeviceRouteRouteChildren: DeviceRouteRouteChildren = {
  DeviceConfirmationRoute: DeviceConfirmationRoute,
  DeviceIndexRoute: DeviceIndexRoute,
}

const DeviceRouteRouteWithChildren = DeviceRouteRoute._addFileChildren(
  DeviceRouteRouteChildren,
)

interface WorkspacesRouteRouteChildren {
  WorkspacesJoinRoute: typeof WorkspacesJoinRoute
}

const WorkspacesRouteRouteChildren: WorkspacesRouteRouteChildren = {
  WorkspacesJoinRoute: WorkspacesJoinRoute,
}

const WorkspacesRouteRouteWithChildren = WorkspacesRouteRoute._addFileChildren(
  WorkspacesRouteRouteChildren,
)

interface AppVaultsRouteChildren {
  AppVaultsVaultIdRoute: typeof AppVaultsVaultIdRoute
  AppVaultsIndexRoute: typeof AppVaultsIndexRoute
}

const AppVaultsRouteChildren: AppVaultsRouteChildren = {
  AppVaultsVaultIdRoute: AppVaultsVaultIdRoute,
  AppVaultsIndexRoute: AppVaultsIndexRoute,
}

const AppVaultsRouteWithChildren = AppVaultsRoute._addFileChildren(
  AppVaultsRouteChildren,
)

interface AppRouteChildren {
  AppAuditRoute: typeof AppAuditRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppMembersRoute: typeof AppMembersRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppVaultsRoute: typeof AppVaultsRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAuditRoute: AppAuditRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppMembersRoute: AppMembersRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppVaultsRoute: AppVaultsRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DeviceRouteRoute: DeviceRouteRouteWithChildren,
  WorkspacesRouteRoute: WorkspacesRouteRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
